### ISSUE TITLE
jquery-lang.js: 80 Line Number 'fn undefined

### ISSUE THREAD

**Issue by pvnkk** [Irrelon/jquery-lang-js#104] opened 2017-08-03 07:01 UTC
Uncaught TypeError: Cannot read property 'fn' of undefined
    at Lang.init (jquery-lang.js:80)
    at index.html:21

**Comment by abdullaziz89** [comment] 2017-08-10 14:00
i have the same error !!!
anyone can have answer for this ??

**Comment by Irrelon** [comment] 2017-08-10 15:09
Did you guys take a look at the code on line 80? It is extending jQuery. If $ is not defined then it will not work. You need to load jQuery first.

**Comment by abdullaziz89** [comment] 2017-08-10 15:32
the problem not in $ sign .. its on 'fn' of iundefined !!!
the jquery already loaded

**Comment by Irrelon** [comment] 2017-08-10 15:34
But the error is "Cannot read property 'fn' of undefined"

That means it is trying to access the 'fn' property of the $ object and cannot... which means that $ is undefined.

**Comment by abdullaziz89** [comment] 2017-08-10 15:42
<img width="1402" alt="screen shot 2017-08-10 at 6 41 13 pm" src="https://user-images.githubusercontent.com/30901928/29178893-91750d52-7dfb-11e7-8613-f783b39b36ee.png">

**Comment by Irrelon** [comment] 2017-08-10 16:06
Fixed by https://github.com/Irrelon/jquery-lang-js/commit/af68d4ae776a971914b2bf5aef4e05acebf16d21 - the issue was that jQuery was no longer being passed into the lang library by the initial call so $ was undefined.

This was caused by a previous pull request. I've fixed the code. Please download the latest version.

**Closed** 2017-08-10 16:07 UTC
